export const LOAD_FILMS = 'LOAD_FILMS'
export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS'

export const LOAD_FILM_DETAILS = 'LOAD_FILM_DETAILS'
export const LOAD_FILM_DETAILS_SUCCESS = 'LOAD_FILM_DETAILS_SUCCESS'

export const LOAD_GENRES = 'LOAD_GENRES'
export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS'

export const LOAD_GENRE_FILMS = 'LOAD_GENRE_FILMS'
export const LOAD_GENRE_FILMS_SUCCESS = 'LOAD_GENRE_FILMS_SUCCESS'

export const SEARCH_FILMS = 'SEARCH_FILMS'
export const SEARCH_FILMS_SUCCESS = 'SEARCH_FILMS_SUCCESS'

export const ERROR = 'ERROR'